//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 12.0.21005.1
// 
namespace DemoApp.DataReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="show", Namespace="http://tempuri.org/")]
    public partial class show : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string NewsHeadField;
        
        private string NewsDetailField;
        
        private string PictureField;
        
        private string SourceField;
        
        private string dateField;
        
        private string NewsDescriptionField;
        
        private string Adv2Field;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NewsHead {
            get {
                return this.NewsHeadField;
            }
            set {
                if ((object.ReferenceEquals(this.NewsHeadField, value) != true)) {
                    this.NewsHeadField = value;
                    this.RaisePropertyChanged("NewsHead");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NewsDetail {
            get {
                return this.NewsDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.NewsDetailField, value) != true)) {
                    this.NewsDetailField = value;
                    this.RaisePropertyChanged("NewsDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                if ((object.ReferenceEquals(this.dateField, value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string NewsDescription {
            get {
                return this.NewsDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.NewsDescriptionField, value) != true)) {
                    this.NewsDescriptionField = value;
                    this.RaisePropertyChanged("NewsDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Adv2 {
            get {
                return this.Adv2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Adv2Field, value) != true)) {
                    this.Adv2Field = value;
                    this.RaisePropertyChanged("Adv2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataReference.DataModelSoap")]
    public interface DataModelSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNews", ReplyAction="*")]
        System.Threading.Tasks.Task<DemoApp.DataReference.GetNewsResponse> GetNewsAsync(DemoApp.DataReference.GetNewsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNews", Namespace="http://tempuri.org/", Order=0)]
        public DemoApp.DataReference.GetNewsRequestBody Body;
        
        public GetNewsRequest() {
        }
        
        public GetNewsRequest(DemoApp.DataReference.GetNewsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetNewsRequestBody {
        
        public GetNewsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewsResponse", Namespace="http://tempuri.org/", Order=0)]
        public DemoApp.DataReference.GetNewsResponseBody Body;
        
        public GetNewsResponse() {
        }
        
        public GetNewsResponse(DemoApp.DataReference.GetNewsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNewsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DemoApp.DataReference.show GetNewsResult;
        
        public GetNewsResponseBody() {
        }
        
        public GetNewsResponseBody(DemoApp.DataReference.show GetNewsResult) {
            this.GetNewsResult = GetNewsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataModelSoapChannel : DemoApp.DataReference.DataModelSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataModelSoapClient : System.ServiceModel.ClientBase<DemoApp.DataReference.DataModelSoap>, DemoApp.DataReference.DataModelSoap {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DataModelSoapClient() : 
                base(DataModelSoapClient.GetDefaultBinding(), DataModelSoapClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.DataModelSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataModelSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(DataModelSoapClient.GetBindingForEndpoint(endpointConfiguration), DataModelSoapClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataModelSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DataModelSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataModelSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DataModelSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataModelSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DemoApp.DataReference.GetNewsResponse> DemoApp.DataReference.DataModelSoap.GetNewsAsync(DemoApp.DataReference.GetNewsRequest request) {
            return base.Channel.GetNewsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DemoApp.DataReference.GetNewsResponse> GetNewsAsync() {
            DemoApp.DataReference.GetNewsRequest inValue = new DemoApp.DataReference.GetNewsRequest();
            inValue.Body = new DemoApp.DataReference.GetNewsRequestBody();
            return ((DemoApp.DataReference.DataModelSoap)(this)).GetNewsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.DataModelSoap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.DataModelSoap)) {
                return new System.ServiceModel.EndpointAddress("http://virtualmic.cloudapp.net/DataModel.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return DataModelSoapClient.GetBindingForEndpoint(EndpointConfiguration.DataModelSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return DataModelSoapClient.GetEndpointAddress(EndpointConfiguration.DataModelSoap);
        }
        
        public enum EndpointConfiguration {
            
            DataModelSoap,
        }
    }
}
